import Head from "next/head";
import AboutPage from "../components/AboutPage";

export default function About() {
  return (
    <div>
      <Head>
        <title>about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutPage />
    </div>
  );
}
