import Head from "next/head";

import DashboardPage from "../components/DashboardPage";

export default function Dashboard({data}) {
  
  return (
    <div>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardPage />
    </div>
  );
}
