import Head from "next/head";
import IndividualPage from "../components/IndividualPage";
import pic from "../public/assets/lizpic.jpg"
export default function TestPage() {
  return (
    <div>
      <Head>
        <title>Elizabeth Kirwan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndividualPage name="Elizabeth Kirwan" role="Front End" 
      animal="Bear" picture={pic}/>
    </div>
  );
}