import Head from "next/head";
import IndividualPage from "../components/IndividualPage";
import pic from "../public/assets/thanos.jpg"
export default function Joshua() {
  return (
    <div>
      <Head>
        <title>Joshua Boelman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndividualPage name="Joshua Boelman" role="Team Lead" 
      animal="Falcon" picture={pic}/>
    </div>
  );
}