import Head from "next/head";
import IndividualPage from "../components/IndividualPage";
import pic from "../public/assets/kennethpic.jpg"
export default function Kenneth() {
  return (
    <div>
      <Head>
        <title>Kenneth Galang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndividualPage name="Kenneth Galang" role="Github Master" 
      animal="Pigeon" picture={pic}/>
    </div>
  );
}