import Head from "next/head";

import KennethPage from "../components/KennethPage";

export default function Kenneth() {
  return (
    <div>
      <Head>
        <title>Kenneth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <KennethPage />
    </div>
  );
}