
import LoginPage from '../components/LoginPage'

import Head from "next/head";



export default function Login() {

  return (
      <>
    <Head>
    <title>Login</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <LoginPage/>
    </>
  )
}

{/* <Account key={session.user.id} session={session} /> */}