import Head from "next/head";
import IndividualPage from "../components/IndividualPage";
import pic from "../public/assets/bunny.jpg";

export default function Madeleine() {
  return (
    <div>
      <Head>
        <title>Madeleine De Mesa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndividualPage
        name="Madeleine De Mesa"
        role="Scrum Master"
        animal="Seals"
        picture={pic}
      />
    </div>
  );
}
